#training List
trainning_list:
  - "./conf/Claude31_50.yml"
  - "./conf/Claude31_150.yml"
  - "./conf/Claude31_200.yml"
  - "./conf/Claude31_220.yml"
  - "./conf/Claude31_250.yml"
  - "./conf/Claude31_300.yml"
  - "./conf/Claude31_320.yml"
