#training List
trainning_list:
  - "./conf/Raphael_5_200.yml"
  - "./conf/Raphael_5_280.yml"
  - "./conf/Raphael_5_300.yml"
  - "./conf/Raphael_5_330.yml"
  - "./conf/Raphael_5_350.yml"
  - "./conf/Raphael_5_400.yml"
  - "./conf/Raphael_5_500.yml"