#training List
trainning_list:
  - "./conf/paint_300.yml"
  - "./conf/paint_400.yml"
  - "./conf/paint_500.yml"
  - "./conf/paint_600.yml"
  - "./conf/paint_700.yml"
  - "./conf/paint_800.yml"
  - "./conf/paint_900.yml"
  - "./conf/paint_1000.yml"