#training List
trainning_list:
  - "./conf/Andy_Warhol_57_50.yml"
  - "./conf/Andy_Warhol_57_100.yml"
  - "./conf/Andy_Warhol_57_150.yml"
  - "./conf/Andy_Warhol_57_200.yml"
  - "./conf/Andy_Warhol_58_50.yml"
  - "./conf/Andy_Warhol_58_100.yml"
  - "./conf/Andy_Warhol_58_150.yml"
  - "./conf/Andy_Warhol_58_200.yml"
  - "./conf/Andy_Warhol_59_50.yml"
  - "./conf/Andy_Warhol_59_100.yml"
  - "./conf/Andy_Warhol_59_150.yml"
  - "./conf/Andy_Warhol_59_200.yml"