#training List
trainning_list:
  - "./conf/cstyle1_50.yml"
  - "./conf/cstyle1_100.yml"
  - "./conf/cstyle1_150.yml"
  - "./conf/cstyle1_200.yml"
  - "./conf/cstyle1_250.yml"
  - "./conf/cstyle1_350.yml"
  - "./conf/cstyle1_450.yml"
  - "./conf/cstyle1_550.yml"
  - "./conf/cstyle2_50.yml"
  - "./conf/cstyle2_100.yml"
  - "./conf/cstyle2_150.yml"
  - "./conf/cstyle2_200.yml"
  - "./conf/cstyle2_250.yml"
  - "./conf/cstyle2_350.yml"
  - "./conf/cstyle2_450.yml"
  - "./conf/cstyle2_550.yml"
  - "./conf/cstyle3_50.yml"
  - "./conf/cstyle3_100.yml"
  - "./conf/cstyle3_150.yml"
  - "./conf/cstyle3_200.yml"
  - "./conf/cstyle3_250.yml"
  - "./conf/cstyle3_350.yml"
  - "./conf/cstyle3_450.yml"
  - "./conf/cstyle3_550.yml"
  - "./conf/cstyle4_50.yml"
  - "./conf/cstyle4_100.yml"
  - "./conf/cstyle4_150.yml"
  - "./conf/cstyle4_200.yml"
  - "./conf/cstyle4_250.yml"
  - "./conf/cstyle4_350.yml"
  - "./conf/cstyle4_450.yml"
  - "./conf/cstyle4_550.yml"
  - "./conf/cstyle5_50.yml"
  - "./conf/cstyle5_100.yml"
  - "./conf/cstyle5_150.yml"
  - "./conf/cstyle5_200.yml"
  - "./conf/cstyle5_250.yml"
  - "./conf/cstyle5_350.yml"
  - "./conf/cstyle5_450.yml"
  - "./conf/cstyle5_550.yml"